require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false

project 'AwesomeTSProject', {
  'DebugDev' => :debug,
  'DebugPreprod' => :debug,
  'DebugProd' => :debug,
  'ReleaseDev' => :release,
  'ReleasePreprod' => :release,
  'ReleaseProd' => :release,
}

target 'AwesomeTSProject' do
  config = use_native_modules!
  debugs = ['DebugDev', 'DebugPreprod', 'DebugProd']
  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'AwesomeTSProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!(configurations: debugs)
  #  use_flipper!(configurations: ['DevDebug', 'ProdDebug'])

  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
        config.build_settings["BUILD_LIBRARY_FOR_DISTRIBUTION"] = "YES"
    end
    end
  end
end
